### ISSUE TITLE
New events 2,7,6    

### ISSUE THREAD

**Issue by Francisk0** [Mickaelh51/rsi-alarm-gateway#12]
[2023-07-30 18:04:17,054] - server - INFO - ### Connected with 192.168.100.11:41049 ###                                                                                                          
[2023-07-30 18:04:17,055] - server - INFO - Start new thread: 140683861052192                                                                                                                    
[2023-07-30 18:04:17,055] - server - INFO - Number of threads: 3                                                                                                                                 
[2023-07-30 18:04:17,078] - utils - INFO - serial: E8B0502063080508                                                                                                                              
[2023-07-30 18:04:17,078] - utils - INFO - key: 50880052600010030058520060018800                                                                                                                 
[2023-07-30 18:04:17,078] - utils - INFO - Setting preshared key                                                                                                                                 
[2023-07-30 18:04:17,079] - utils - INFO - Generate new challenge: B32C8B826515165FF76FFC763DEE2B00                                                                                              
[2023-07-30 18:04:17,297] - utils - INFO - Key response to alarm: FA3B0D970BA288165A472236875E38AF                                                                                               
[2023-07-30 18:04:17,860] - utils - INFO - Answer: AUTH_SUCCESS,0000,5,20230730200411,5,2,E6612124110,0,XLP090128,0,27FF                                                                         
[2023-07-30 18:04:17,860] - utils - INFO - Logging successful !!                                                                                                                                 
[2023-07-30 18:04:18,858] - server - DEBUG - b'FILE,2676,armstatus.json\x1a'                                                                                                                     
[2023-07-30 18:04:18,858] - server - INFO - We received FILE                                                                                                                                     
[2023-07-30 18:04:19,030] - server - DEBUG - b'{"FileVersion":2,"L10nRef":"armsta1","DateTime":"2023-07-30 20:04:11","Panel":{"AccountNumber":"0000","SerialNumber":"E8B0502063080508","Anomaly.e
num":null},"GeneralConfiguration":{"PartitionActive":false,"XtenderActive":false,"Normal":{"ArmMode.enum":[1,1,1,1]},"SP1":{"Name":"SP1","ArmMode.enum":null},"SP2":{"Name":"SP2","ArmMode.enum":
null},"ExitDelay":120,"LookInPrivacyEnabled":false},"Devices":[{"DeviceIndex":2,"DeviceByTypeIndex":1,"DetectorIndex":1,"SerialNumber":"A14E1788","Name":"CAM CHIMENEA","External":false,"Perimet
ral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex":3,"DeviceByTypeIndex":2,"DetectorIndex":2,"SerialNumber":"2399049C","Name":"CAM SALO
N2","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex":4,"DeviceByTypeIndex":3,"DetectorIndex":3,"SerialNumber
":"03990472","Name":"CAM PASILLO","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex":5,"DeviceByTypeIndex":4,"
DetectorIndex":4,"SerialNumber":"814E31DA","Name":"CAM BBQ","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex"
:6,"DeviceByTypeIndex":5,"DetectorIndex":5,"SerialNumber":"03990287","Name":"CAM GARAJE","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependan
tF'                                                                                                                                                                                              
[2023-07-30 18:04:19,030] - server - INFO - We received json file, send ACK                                                                                                                      
[2023-07-30 18:04:19,102] - server - DEBUG - b'ields":null},{"DeviceIndex":7,"DeviceByTypeIndex":1,"DetectorIndex":6,"SerialNumber":"C108015F","Name":"PUERTA PISCINA","External":true,"Perimetra
l":true,"Type.enum":8,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":{"Delay":0}},{"DeviceIndex":8,"DeviceByTypeIndex":2,"DetectorIndex":7,"SerialNumber":"C11806F8","Name":"PUER
TA PORCHE","External":true,"Perimetral":true,"Type.enum":8,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":{"Delay":0}},{"DeviceIndex":9,"DeviceByTypeIndex":3,"DetectorIndex":8,"
SerialNumber":"C1180314","Name":"PUERTA COCINA","External":true,"Perimetral":true,"Type.enum":8,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":{"Delay":0}}],"Areas":[{"Name":"PL
ANTA BAJA","Delayed":true,"Devices":[2,3,7,8,9],"ArmStatus.enum":1},{"Name":"PLANTA ALTA","Delayed":false,"Devices":[4],"ArmStatus.enum":1},{"Name":"GARAJE BARBACOA","Delayed":false,"Devices":[
5,6],"ArmStatus.enum":1},{"Name":"ZONA  4","Delayed":false,"Devices":null,"ArmStatus.enum":1}],"Area24":{"Devices":null},"Partitions":[{"Name":"PA1","Areas":[1,2],"ArmStatus.enum":1},{"Name":"P
A2","Areas":[3,4],"ArmStatus.enum":1}],"StandardArmStatus.enum":2}\x1a'                                                                                                                          
[2023-07-30 18:04:24,107] - server - INFO - No data from client                                                                                                                                  
[2023-07-30 18:04:24,107] - server - INFO - ### Connection 192.168.100.11:41049 closed ###                                                                                                       
[2023-07-30 18:08:27,677] - server - INFO - ### Connected with 192.168.100.11:27909 ###                                                                                                          
[2023-07-30 18:08:27,678] - server - INFO - Start new thread: 140683861052192                                                                                                                    
[2023-07-30 18:08:27,678] - server - INFO - Number of threads: 3                                                                                                                                 
[2023-07-30 18:08:27,691] - utils - INFO - serial: E8B0502063080508                                                                                                                              
[2023-07-30 18:08:27,692] - utils - INFO - key: 50880052600010030058520060018800                                                                                                                 
[2023-07-30 18:08:27,692] - utils - INFO - Setting preshared key   
[2023-07-30 18:08:27,693] - utils - INFO - Generate new challenge: 751CEBE3A6E2A2C4975DF4C18FAA26C7                                                                                              
[2023-07-30 18:08:27,910] - utils - INFO - Key response to alarm: FCD646EF26ED6BFA813983B1CEDE8524                                                                                               
[2023-07-30 18:08:28,483] - utils - INFO - Answer: AUTH_SUCCESS,0000,5,20230730200822,5,2,E6612124110,0,XLP090128,0,27FF                                                                         
[2023-07-30 18:08:28,484] - utils - INFO - Logging successful !!                                                                                                                                 
[2023-07-30 18:08:28,580] - server - DEBUG - b'ALARM,1932\x1a'                                                                                                                                   
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0b\x00INPUT1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1b\x1a\x04\x00OUTPUT1\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1b\x1b\x04\x00OUTPUT2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1b\x1c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004B4303181118011A\x00\x00\x00\x00\x01\x008C040421A14E1788\x00\x00\x00\x00\x01\x008C0405172399049C\x00\x00\x00\x00\x
01\x008C04481703990472\x00\x00\x00\x00\x01\x008C043020814E31DA\x00\x00\x00\x00\x01\x008C0427170399'                                                                                              
[2023-07-30 18:08:28,753] - server - DEBUG - b'STATUS\x00\x00\x00\x00FC2043000\x001932\x00\x00\x00\x00\x00\x00\x01\x00 \x1b\x1c\x00\x00\x00\x00\x00\x00\n\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00757606\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04PLANTA BAJA\x00\x00\x00\x00\x00\x00A\x00\x00PLANTA ALTA\x00\x00\x00\x00\x00\x00A\x00\x
00GARAJE BARBACOA\x00\x00A\x00\x00    ZONA  4\x00\x00\x00\x00\x00\x00A\x00\x00\t\x01\x01TECLADO\x011\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x06\x01CAM CHIMENEA\x00\x00\x00\x00\x00\x00\x00\
x02\x06\x01CAM SALON2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x06\x02CAM PASILLO\x00\x00\x00\x00\x00\x00\x00\x00\x04\x06\x03CAM BBQ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x06\x03CA
M GARAJE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x08\x01PUERTA PISCINA\x00\x00\x00\x00\x00\x07\x08\x01PUERTA PORCHE\x00\x00\x00\x00\x00\x00\x08\x08\x01PUERTA COCINA\x00\x00\x00\x00\x00\x00\t\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\[2023-07-30 18:08:28,781] - server - DEBUG - b'0287\x00\x00\x00\x00\x01\x0080023916C108015F\x00\x00\x00\x00\x01\x0080020417C11806F8\x00\x00\x00\x00\x0
1\x0080022920C1180314\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00
\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\
x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x0000000000000000
00\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x000000000000000000\x00\x00\x00\x00\x00\x00\xff\x01\x05\x01\x01\x00\x00\x00\x00\x1a'                                              
[2023-07-30 18:08:28,860] - server - DEBUG - b'EVENT,1,7,6\x1a'                                                                                                                                  
[2023-07-30 18:08:28,860] - server - INFO - We received EVENT: EVENT,1,7,6                                                                                                                       
[2023-07-30 18:08:28,861] - server - INFO - Received update from alarm (alarm alert !) update MQTT / source of event (Sensor noid 7) / zone of event (BBQ y Garaje)                              
[2023-07-30 18:08:28,960] - server - DEBUG - b'EVENT,2,7,6\x1a'                                                                                                                                  
[2023-07-30 18:08:28,961] - server - INFO - We received EVENT: EVENT,2,7,6                                                                                                                       
[2023-07-30 18:08:28,961] - utils - ERROR - unable to find event type (EVENT,2,7,6)                                                                                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/usr/src/app/utils.py", line 68, in find_event_type                                                                                                                                      
    event_type = cfg["mapping_events"][event_array[1]]                                                                                                                                           
KeyError: '2'
[2023-07-30 18:08:29,061] - server - DEBUG - b'EVENT,1,3,2\x1a'                                                                                                                                  
[2023-07-30 18:08:29,061] - server - INFO - We received EVENT: EVENT,1,3,2                                                                                                                       
[2023-07-30 18:08:29,062] - server - INFO - Received update from alarm (alarm alert !) update MQTT / source of event (Sensor noid 3) / zone of event (Planta Baja)                               
[2023-07-30 18:08:29,160] - server - DEBUG - b'EVENT,1,2,1\x1a'                                                                                                                                  
[2023-07-30 18:08:29,160] - server - INFO - We received EVENT: EVENT,1,2,1                                                                                                                       
[2023-07-30 18:08:29,161] - server - INFO - Received update from alarm (alarm alert !) update MQTT / source of event (Sensor noid 2) / zone of event (Planta Baja)                               
[2023-07-30 18:08:29,260] - server - DEBUG - b'EVENT,2,3,2\x1a'                                                                                                                                  
[2023-07-30 18:08:29,260] - server - INFO - We received EVENT: EVENT,2,3,2                                                                                                                       
[2023-07-30 18:08:29,261] - utils - ERROR - unable to find event type (EVENT,2,3,2)                                                                                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/usr/src/app/utils.py", line 68, in find_event_type                                                                                                                                      
    event_type = cfg["mapping_events"][event_array[1]]                                                                                                                                           
KeyError: '2'                                                                                                                                                                                    
[2023-07-30 18:08:29,360] - server - DEBUG - b'EVENT,2,2,1\x1a'                                                                                                                                  
[2023-07-30 18:08:29,360] - server - INFO - We received EVENT: EVENT,2,2,1                                                                                                                       
[2023-07-30 18:08:29,361] - utils - ERROR - unable to find event type (EVENT,2,2,1)                                                                                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/usr/src/app/utils.py", line 68, in find_event_type                                                                                                                                      
    event_type = cfg["mapping_events"][event_array[1]]                                                                                                                                           
KeyError: '2'                                                                                                                                                                                    
[2023-07-30 18:08:29,460] - server - DEBUG - b'LOG,152,20\x1a'                                                                                                                                   
[2023-07-30 18:08:29,571] - server - DEBUG - b'LOG\x00\x00\x00\x00\x00\x00\x00FC2043000\x00152\x00\x00\x00\x00\x00\x00\x00\x14\x00\xd7y\x8a\x1b\x1c\x00p\xd7yJ\xe4\x05J\xd7yJ \x03C\xd7yJ \x00k\x
d7y*t\x02m\xd7y\x1b\x1a\xc0\x03m\xd7y\x1b\x1a\x00\x00S\xd7y\x1b\x1a\x00\x02P\xd7y\x1b\x1a\x00\x00S\xd7y\x1b\x1a\x00\x03P\xd7y\x1b\x1a\x00\x07m\xd7y\x1b\x1a\x00\x07P\xd7\xf9\xa9\x8b\x00b\xd7\xf9
\xa9s\x01?\xd7\xf9\x89s\x01\x86\xd7\xf9\x89S\x00k\xd7\xf9Y/\x00b\xd7\xf9I\xef\x00k\xd7\xf9\x19\xcb\x00b\xd7\xf9\x19\xbf\x1fl\x1a'                                                                
[2023-07-30 18:08:30,564] - server - DEBUG - b'FILE,2676,armstatus.json\x1a'                                                                                                                     
[2023-07-30 18:08:30,564] - server - INFO - We received FILE                                                                                                                                     
[2023-07-30 18:08:30,739] - server - DEBUG - b'{"FileVersion":2,"L10nRef":"armsta1","DateTime":"2023-07-30 20:08:23","Panel":{"AccountNumber":"0000","SerialNumber":"E8B0502063080508","Anomaly.e
num":null},"GeneralConfiguration":{"PartitionActive":false,"XtenderActive":false,"Normal":{"ArmMode.enum":[1,1,1,1]},"SP1":{"Name":"SP1","ArmMode.enum":null},"SP2":{"Name":"SP2","ArmMode.enum":
null},"ExitDelay":120,"LookInPrivacyEnabled":false},"Devices":[{"DeviceIndex":2,"DeviceByTypeIndex":1,"DetectorIndex":1,"SerialNumber":"A14E1788","Name":"CAM CHIMENEA","External":false,"Perimet
ral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex":3,"DeviceByTypeIndex":2,"DetectorIndex":2,"SerialNumber":"2399049C","Name":"CAM SALO
N2","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex":4,"DeviceByTypeIndex":3,"DetectorIndex":3,"SerialNumber
":"03990472","Name":"CAM PASILLO","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex":5,"DeviceByTypeIndex":4,"
DetectorIndex":4,"SerialNumber":"814E31DA","Name":"CAM BBQ","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":null},{"DeviceIndex"
:6,"DeviceByTypeIndex":5,"DetectorIndex":5,"SerialNumber":"03990287","Name":"CAM GARAJE","External":false,"Perimetral":false,"Type.enum":6,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependan
tF'                                                                                                                                                                                              
[2023-07-30 18:08:30,739] - server - INFO - We received json file, send ACK                                                                                                                      
[2023-07-30 18:08:30,808] - server - DEBUG - b'ields":null},{"DeviceIndex":7,"DeviceByTypeIndex":1,"DetectorIndex":6,"SerialNumber":"C108015F","Name":"PUERTA PISCINA","External":true,"Perimetra
l":true,"Type.enum":8,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":{"Delay":0}},{"DeviceIndex":8,"DeviceByTypeIndex":2,"DetectorIndex":7,"SerialNumber":"C11806F8","Name":"PUER
TA PORCHE","External":true,"Perimetral":true,"Type.enum":8,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":{"Delay":0}},{"DeviceIndex":9,"DeviceByTypeIndex":3,"DetectorIndex":8,"
SerialNumber":"C1180314","Name":"PUERTA COCINA","External":true,"Perimetral":true,"Type.enum":8,"ArmStatus.enum":2,"Anomaly.enum":null,"DeviceDependantFields":{"Delay":0}}],"Areas":[{"Name":"PL
ANTA BAJA","Delayed":true,"Devices":[2,3,7,8,9],"ArmStatus.enum":1},{"Name":"PLANTA ALTA","Delayed":false,"Devices":[4],"ArmStatus.enum":1},{"Name":"GARAJE BARBACOA","Delayed":false,"Devices":[
5,6],"ArmStatus.enum":1},{"Name":"ZONA  4","Delayed":false,"Devices":null,"ArmStatus.enum":1}],"Area24":{"Devices":null},"Partitions":[{"Name":"PA1","Areas":[1,2],"ArmStatus.enum":1},{"Name":"P
A2","Areas":[3,4],"ArmStatus.enum":1}],"StandardArmStatus.enum":2}\x1a'                                                                                                                          
[2023-07-30 18:08:30,845] - server - DEBUG - b'REQACK,0\x1a'                                                                                                                                     
[2023-07-30 18:08:30,845] - server - INFO - We received REQACK, send simple ACK                                                                                                                  
[2023-07-30 18:08:35,851] - server - INFO - No data from client

**Comment by Mickaelh51** [comment]
You can add 2,7,6 code in configuration
https://github.com/Mickaelh51/rsi-alarm-gateway/blob/master/config.json.example
EVENT,2,p,d Intrusion DIS
p = Item number (panel = 62)
d = Detector number (this field is optional and should be ignored)

and create a PR

Ex: 
2 => https://github.com/Mickaelh51/rsi-alarm-gateway/blob/91975e1b4fc987272a916980cf95110495ec15c2/config.json.example#L24

7 => https://github.com/Mickaelh51/rsi-alarm-gateway/blob/91975e1b4fc987272a916980cf95110495ec15c2/config.json.example#L50



thanks in advance
